### ISSUE TITLE
Place split Use Meta Variables - Replace UUID and dates in two

### ISSUE THREAD

**Issue by bjornbak** [mediaworx/opencms-intellijplugin#4]
We use your great opencms plugin in IntelliJ but experience problems when Use Meta Variables - Replace UUID and dates is enabled.

The problems arise when one developer creates an element or formatter and uses it in a page and another developer synchronizes the element into vfs. Now it has another UUID and the reference no longer work.

I learned on OpenCms Days that the purpose of the setting is to avoid merge conflicts but I think these primarily happens in the dates?

Please split the Use Meta Variables - Replace UUID and dates in two so we can use placeholders for dates and not UUID.

**Comment by kaiwidmann** [comment]
Well actually we had almost the same merge problems with UUIDs as we had with dates. If developer A creates a new resource (formatter, element, whatever) and developer B gets this from Git and does a Sync, the resource is newly created in the VFS on developer B's instance and gets a new UUID (as you described), so the meta file contains a different UUID. And if multiple devs do this it's merge conflict galore. So it's really choosing the lesser evil, which for us was getting rid of the UUIDs altogether and generating them whenever the manifest is created. 
The reason for all this is that we can't sync resources with all their meta data the way we would like to, because the CMIS interface that's used for syncing can't do this. I can't tell OpenCms to use a specific UUID when a new resource is created through CMIS. That's a flaw we are aware of and we want to change, but we will have to write our own sync mechanism instead of using a standard, and that might take a while. But it's on top of our TODO list.
May I ask what problems you did have? We got rid of the UUIDs about a year ago and didn't have any trouble regarding formatters or elements. Usually if OpenCms can't find the resource via UUID it tries to use the resource path to identify the resource. We are only having some trouble with template/model pages when element settings are used.
As for your original question: Yes, splitting up the setting and integrating two checkboxes can be done and would be a good thing, but it won't happen before December because it's not done within a few minutes. It has to be implemented on multiple levels and right now all our developers are tied up in projects.

**Comment by bjornbak** [comment]
I'm not entirely sure how it happens and my first scenario might not be
correct.

This scenario might be more correct.

We have (missing the new git function of opencms 10) created a script which
dumps the opencms db on prod and restores the db locally inorder for the
developers to work with real data.

On prod an element or formatter has been used in a page.

Then we sync and gets the ocmsfile file the UUID of the element or
formatter is replaced with the placeholder.

When we later update the element or formatter in IntelliJ and sync it into
opencms we experience it gets a new UUID.

This results in an error when loading the page because it can't find the
UUID.

Turning off the placeholders has worked for us and is a workaround for now.

Med venlig hilsen / Kind regards,

Christian Bjørnbak

Chefudvikler / Lead Developer
TouristOnline A/S
Islands Brygge 43
2300 København S
Denmark
TLF: +45 32888230
Dir. TLF: +45 32888235

2015-10-01 12:26 GMT+02:00 Kai Widmann notifications@github.com:

**Comment by kaiwidmann** [comment]
Hey Christian, 

I've implemented this and it will be in the next release. I'll have to update the Java documentation and GitHub Wiki before releasing. I hope this can be done in December. 
If you would like to get your hands on the new version sooner, I could provide the plugin zip and a new IDEConnector module with some very basic installation / usage instructions.

Cheers

Kai

**Comment by bjornbak** [comment]
Sounds great!

I would love to test a new version of the plugin/IDEConnector :)

Regards,
Christian

Med venlig hilsen / Kind regards,

Christian Bjørnbak

Chefudvikler / Lead Developer
TouristOnline A/S
Islands Brygge 43
2300 København S
Denmark
TLF: +45 32888230
Dir. TLF: +45 32888235

2015-11-04 9:23 GMT+01:00 Kai Widmann notifications@github.com:

**Comment by kaiwidmann** [comment]
It's integrated in the 1.9 release
